# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b36f6a8e76ee2ef9c4a41820bf0ff8965fa8e7e6069885c7c0a312b6a016b7bb7a7485ace816fae3b5b8f97631100edf7eb1745f7c5235f3041f72cac10311e

test:
  secret_key_base: 1784ae7fdcd97991f6d1d2db6e461971da24de44a2ddfb6d29c742e3d362ae5497ddea0424a99a40baf0527f2386c4d2cd2e4fc1c510c43fcaa6b370cda0aec6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
